### ISSUE TITLE
希望能有一个供入门演示的demo项目

### ISSUE THREAD

**Issue by chpengzh** [didi/sds#19]
**Is your feature request related to a problem? Please describe.**

目前我们有了一个演示用的测试环境[https://sds.chpengzh.com](https://sds.chpengzh.com)

希望基于演示用的测试环境提供一些测试代码供用户使用；

**Describe the solution you'd like**

新建一个项目供演示使用

@manzhizhen

**Comment by manzhizhen** [comment]
已经有了：https://github.com/didi/sds/tree/master/sds-example
